### ISSUE TITLE
Missing ./staging directory

### ISSUE THREAD

**Issue by mbl-35** [kaisalmen/wsltooling#2]
After fresh clone of repo:

- use of **installUbuntuLTS.ps1** script (regular or admin users),
- use of **installWSL2.ps1** script (admin users)

the working directory './staging' is not created (ignored on .gitignore file). Curls commands failed.

Is it possible to create dynamically this directory on both scripts (or append it into the to Preparation and Installation parts of the README.md)?
Thanks
mbl

**Comment by kaisalmen** [comment]
@mbl-35 yes, I just pushed an update. Both scripts create the `staging` directory silently if not existing.

**Comment by kaisalmen** [comment]
FYI: I referenced the wrong issue in the commits mentioned above.
